src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/OrgController.cs
using Fireasy.Common.ComponentModel;
using Fireasy.Common.Extensions;
using Fireasy.Web.EasyUI;
using Fireasy.Web.Mvc;
using Fireasy.Zero.Helpers;
using Fireasy.Zero.Models;
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Fireasy.Zero.AspNetCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class OrgController : Controller
    {
        private IAdminService _adminService;

        public OrgController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取机构。
        /// </summary>
        /// <param name="id">信息ID。</param>
        /// <returns></returns>
        public async Task<JsonResult> Get(int id)
        {
            var info = await _adminService.GetOrgAsync(id);
            return Json(info);
        }

        /// <summary>
        /// 获取下一个顺序号。
        /// </summary>
        /// <param name="parentId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetNextOrderNo(int? parentId)
        {
            return Json(await _adminService.GetOrgNextOrderNoAsync(parentId));
        }

        /// <summary>
        /// 保存机构。
        /// </summary>
        /// <param name="id">id。</param>
        /// <param name="info">要保存的数据。</param>
        /// <returns>id</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Save(int? id, SysOrg info)
        {
            id = await _adminService.SaveOrgAsync(id, info);
            return Json(Result.Success("保存成功。", id));
        }

        /// <summary>
        /// 保存多个机构。
        /// </summary>
        /// <param name="parentId">隶属机构ID。</param>
        /// <param name="rows">多个机构数据。</param>
        /// <returns></returns>
        public async Task<JsonResult> SaveRows(int? parentId, List<SysOrg> rows)
        {
            await _adminService.SaveOrgsAsync(parentId, rows);
            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 根据查询条件获取机构。
        /// </summary>
        /// <param name="hosting">用来往 <see cref="JsonSerializeOption"/> 里加自定义的转换器。</param>
        /// <param name="id"></param>
        /// <param name="targetId"></param>
        /// <param name="currentId"></param>
        /// <param name="attribute"></param>
        /// <param name="state"></param>
        /// <param name="attType">附加的信息。</param>
        /// <param name="flag"></param>
        /// <returns></returns>
        public async Task<JsonResult> DataDemand([FromServices] JsonSerializeOptionHosting hosting, int? id, int? targetId, int? currentId, OrgAttribute? attribute = null, StateFlags? state = null, ItemFlag? flag = null)
        {
            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Code, s => s.AttributeName, s => s.State);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetOrgsAsync(id, targetId, currentId, state, null, attribute);

            return Json(id != null ? list : ItemFlagHelper.Insert(list, flag, s => new { id = 0, text = s.GetDescription() }));
        }

        /// <summary>
        /// 根据查询条件获取机构。
        /// </summary>
        /// <param name="hosting">用来往 <see cref="JsonSerializeOption"/> 里加自定义的转换器。</param>
        /// <param name="targetId"></param>
        /// <param name="attribute"></param>
        /// <param name="attType">附加的信息。</param>
        /// <param name="corpType">企业类别。</param>
        /// <param name="flag"></param>
        /// <returns></returns>
        public async Task<JsonResult> Data([FromServices] JsonSerializeOptionHosting hosting, int? targetId, OrgAttribute? attribute = null, ItemFlag? flag = null)
        {
            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Code, s => s.AttributeName, s => s.State);
            hosting.Option.Converters.Add(converter);

            var session = HttpContext.GetSession();

            var list = await _adminService.GetOrgsAsync(session.UserID, null, attribute);
            if (targetId != null)
            {
                await ExpandTargetAsync(list, (int)targetId);
            }

            return Json(ItemFlagHelper.Insert(list, flag, s => new { id = 0, text = s.GetDescription() }));
        }

        /// <summary>
        /// 按关键字搜索。
        /// </summary>
        /// <param name="appKey">应用key。</param>
        /// <param name="keyword">关键字。</param>
        /// <returns></returns>
        public async Task<JsonResult> Search(string keyword)
        {
            var list = await _adminService.SearchOrgsAsync(keyword);
            return Json(list);
        }

        /// <summary>
        /// 删除机构。
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id)
        {
            await _adminService.DeleteOrgAsync(id);
            return Json(Result.Success("删除成功。"));
        }

        /// <summary>
        /// 启用机构。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Enable(int id)
        {
            await _adminService.SetOrgStateAsync(id, StateFlags.Enabled);
            return Json(Result.Success("启用成功。"));
        }

        /// <summary>
        /// 禁用机构。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Disable(int id)
        {
            await _adminService.SetOrgStateAsync(id, StateFlags.Disabled);
            return Json(Result.Success("禁用成功。"));
        }

        /// <summary>
        /// 展开到目标节点。
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        private async Task ExpandTargetAsync(List<SysOrg> list, int parentId)
        {
            var org = await _adminService.GetOrgAsync(parentId);
            if (org == null)
            {
                return;
            }

            var code = org.Code;
            var length = code.Length;
            var children = list;

            for (var i = 0; i < length; i += 2)
            {
                org = children.Find(s => s.Code == code.Substring(0, i + 2));
                if (org != null)
                {
                    org.IsLoaded = true;
                    children = org.Children;
                }
            }
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/PermissionController.cs
using Fireasy.Common.ComponentModel;
using Fireasy.Web.EasyUI;
using Fireasy.Web.Mvc;
using Fireasy.Zero.Helpers;
using Fireasy.Zero.Models;
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Fireasy.Zero.AspNetCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class PermissionController : Controller
    {
        private IAdminService _adminService;

        public PermissionController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectUser()
        {
            return View();
        }

        public ActionResult Function()
        {
            return View();
        }

        public ActionResult Data()
        {
            return View();
        }

        public ActionResult Auth()
        {
            return View();
        }

        /// <summary>
        /// 根据角色获取相应的模块及操作。
        /// </summary>
        /// <param name="hosting"></param>
        /// <param name="roleId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetModulesByRole([FromServices] JsonSerializeOptionHosting hosting, int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var converter = new DynamicTreeNodeJsonConverter<SysModule>(s => s.Name, s => s.Permissible, s => s.SysOperates);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetModulesByRoleAsync((int)roleId);
            return Json(list);
        }

        /// <summary>
        /// 根据角色获取相应的机构。
        /// </summary>
        /// <param name="hosting"></param>
        /// <param name="roleId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetOrgsByRole([FromServices] JsonSerializeOptionHosting hosting, int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Permissible, s => s.FullName);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetOrgsByRoleAsync((int)roleId);
            return Json(list);
        }

        /// <summary>
        /// 获取角色列表。
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetRolesByUser(int userId)
        {
            var list = await _adminService.GetPurviewRolesAsync(userId);
            return Json(list);
        }

        /// <summary>
        /// 根据查询条件获取用户。
        /// </summary>
        /// <param name="orgCode">机构编码</param>
        /// <param name="keyword">关键字</param>
        /// <param name="roleId">角色ID。</param>
        /// <param name="state">启用状态</param>
        /// <returns></returns>
        public async Task<JsonResult> GetUsers(string orgCode, string keyword, int roleId)
        {
            var pager = EasyUIHelper.GetDataPager(HttpContext);
            var sorting = EasyUIHelper.GetSorting(HttpContext);

            var userId = HttpContext.GetSession().UserID;

            sorting = sorting.Replace("SexName", "Sex", "DegreeName", "DegreeNo", "TitleName", "TitleNo");

            var list = await _adminService.GetUsersByRoleExcludeAsync(userId, orgCode, roleId, keyword, pager, sorting);
            return Json(EasyUIHelper.Transfer(pager, list));
        }

        /// <summary>
        /// 保存功能权限。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="modules">勾选的模块ID列表。</param>
        /// <param name="opers">勾选的模块与操作的列表。</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveFuncPermissions(int roleId, List<int> modules, Dictionary<int, List<int>> opers)
        {
            await _adminService.SaveFuncRolePermissions(roleId, modules, opers);

            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 保存数据权限。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="org">勾选的机构ID列表。</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveDataPermissions(int roleId, List<int> orgs)
        {
            await _adminService.SaveOrgRolePermissionsAsync(roleId, orgs);

            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 根据角色获取相应的用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <returns></returns>
        public async Task<JsonResult> GetUsersByRole(int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var pager = EasyUIHelper.GetDataPager(HttpContext);
            var sorting = EasyUIHelper.GetSorting(HttpContext);

            var list = await _adminService.GetUsersByRoleAsync((int)roleId, pager, sorting);

            return Json(EasyUIHelper.Transfer(pager, list));
        }

        /// <summary>
        /// 为角色添加多个用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="users">用户ID列表。</param>
        /// <returns></returns>
        public async Task<JsonResult> AddRoleUsers(int roleId, List<int> users)
        {
            await _adminService.AddRoleUsers(roleId, users);

            return Json(Result.Success("添加成功。"));
        }

        /// <summary>
        /// 移除角色中的指定的用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="users">用户ID列表。</param>
        /// <returns></returns>
        public async Task<JsonResult> DeleteRoleUsers(int roleId, List<int> users)
        {
            await _adminService.DeleteRoleUsers(roleId, users);

            return Json(Result.Success("删除成功。"));
        }

        /// <summary>
        /// 保存用户角色。
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="roles"></param>
        /// <returns></returns>
        public async Task<JsonResult> SaveUserRoles(int userId, List<int> roles)
        {
            await _adminService.SaveUserRoles(userId, roles);

            return Json(Result.Success("保存成功。"));
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/RoleController.cs
using Fireasy.Common.ComponentModel;
using Fireasy.Web.EasyUI;
using Fireasy.Zero.Models;
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Fireasy.Zero.AspNetCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class RoleController : Controller
    {
        private IAdminService _adminService;

        public RoleController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取角色。
        /// </summary>
        /// <param name="id">信息ID。</param>
        /// <returns></returns>
        public async Task<JsonResult> Get(int id)
        {
            var info = await _adminService.GetRoleAsync(id);
            return Json(info);
        }

        /// <summary>
        /// 根据查询条件获取角色。
        /// </summary>
        /// <param name="state">启用状态</param>
        /// <param name="keyword">关键字</param>
        /// <returns></returns>
        public async Task<JsonResult> Data(StateFlags? state, string keyword)
        {
            var pager = EasyUIHelper.GetDataPager(HttpContext);
            var sorting = EasyUIHelper.GetSorting(HttpContext);

            var list = await _adminService.GetRolesAsync(state, keyword, pager, sorting);
            return Json(list);
        }

        /// <summary>
        /// 保存角色。
        /// </summary>
        /// <param name="id">id。</param>
        /// <param name="info">要保存的数据。</param>
        /// <returns>id</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Save(int? id, SysRole info)
        {
            id = await _adminService.SaveRoleAsync(id, info);
            return Json(Result.Success("保存成功。", id));
        }

        /// <summary>
        /// 删除角色。
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id)
        {
            await _adminService.DeleteRoleAsync(id);
            return Json(Result.Success("删除成功。"));
        }

        /// <summary>
        /// 启用角色。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Enable(int id)
        {
            await _adminService.SetRoleStateAsync(id, StateFlags.Enabled);
            return Json(Result.Success("启用成功。"));
        }

        /// <summary>
        /// 禁用角色。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Disable(int id)
        {
            await _adminService.SetRoleStateAsync(id, StateFlags.Disabled);
            return Json(Result.Success("禁用成功。"));
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Views/Permission/Data.cshtml
@{
    ViewBag.Title = "数据授权";
    Layout = "~/Views/Shared/_EasyUILayout.cshtml";
}

<script type="text/javascript">
    var roleId = 0;

    $(function () {
        loadRoles();
        loadOrgs();
        loadUsers();
    });

    function loadRoles() {
        $('#dgRole').datalist({
            url: '@Url.Action("Data", "Role", new { area = "Admin" })',
            fit: true,//自动填充
            singleSelect: true,//单选
            pagination: false,//分页信息
            idField: 'RoleID',
            border: false,
            valueField: 'RoleID',
            textField: 'Name',
            onClickRow: function (index, row) {
                roleId = row.RoleID;
                loadOrgs();
                loadUsers();
            },
            queryParams: { state: '1' }
        });
    }

    function loadUsers() {
        $('#dgUser').datagrid({
            url: '@Url.Action("GetUsersByRole")?roleId=' + roleId,
            fit: true,//自动填充
            singleSelect: true,//单选
            pagination: true,//分页信息
            rownumbers: true,//显示行号
            pageNumber: 1,//默认显示第一页
            pageSize: 20,//每页的行数
            checkOnSelect: false,
            selectOnCheck: false,
            idField: 'UserID',
            columns: [[

                { field: 'ck', checkbox: true },
                { field: 'Name', title: '姓名', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'OrgName', title: '隶属机构', width: 350, halign: 'center', align: 'left', sortable: true },
                { field: 'Account', title: '帐号', width: 120, halign: 'center', align: 'center', sortable: true }
            ]],
            queryParams: { state: '1' }
        });
    }

    //加载数据
    function loadOrgs() {
        $('#dgOrg').treegrid({
            url: '@Url.Action("GetOrgsByRole")?roleId=' + roleId,
            fit: true,//自动填充
            idField: 'id',
            treeField: 'Name',
            columns: [[

                { field: 'Name', title: '名称', width: 260, halign: 'center', align: 'left', formatter: function (value, row) { return formatCheckbox(value, row); } },
                { field: 'FullName', title: '全称', width: 600, halign: 'center', align: 'left' }
            ]]
        });
    }

    function formatCheckbox(value, row) {
        return '<input did="' + row.id + '" type="checkbox" ' + (row.Permissible ? 'checked' : '') + ' />' + value;
    }

    function addUser() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        common.showDialog('@Url.Action("SelectUser")?roleId=' + roleId, '选择用户', 1080, 550, function (users) {
            var postData = new Object();
            postData.roleId = roleId;
            postData.users = JSON.stringify(users);
            $.post('@Url.Action("AddRoleUsers")', postData, function (result) {
                $('#dgUser').datagrid('reload');
            })
        }).max();
    }

    function deleteUser() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        var rows = $('#dgUser').datagrid('getChecked');
        if (rows.length == 0) {
            common.alert('请选择要移除的用户。');
            return;
        }

        var ids = [];
        $.each(rows, function (i, r) {
            ids.push(r.UserID);
        });

        common.confirm('是否从当前角色中移除指定的用户?', function () {
            var postData = new Object();
            postData.roleId = roleId;
            postData.users = JSON.stringify(ids);
            $.post('@Url.Action("DeleteRoleUsers")', postData, function (result) {
                $('#dgUser').datagrid('reload');
            })
        });
    }

    function saveInfo() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        common.confirm('是否保存权限?', function () {
            var checked = $('input[did]:checked');
            var data = [];
            $.each(checked, function (i, c) {
                var did = $(c).attr('did');
                data.push(did);
            })

            var postData = new Object();
            postData.roleId = roleId;
            postData.orgs = JSON.stringify(data);

            common.showProcess();

            $.post('@Url.Action("SaveDataPermissions")', postData, function (result) {
                common.processResult(result);
            })
        });
    }
</script>
@Html.AntiForgeryToken()
<div data-options="region:'west',border:false,split:true,collapsible:true,title:'角色'" style="width:160px">
    <table id="dgRole" style="width:100%"></table>
</div>
<div data-options="region:'center',border:false">
    <div class="easyui-tabs" data-options="fit:true" style="width: 100%; height: 100%">
        <div title="权限设置">
            <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
                <div data-options="region:'north',border:false">
                    <div class="datagrid-toolbar">
                        <a key="Save" class="easyui-linkbutton" onclick="saveInfo()" data-options="iconCls: 'icon-ok', plain: true">保存</a>
                    </div>
                </div>
                <div data-options="region:'center',border:false">
                    <table id="dgOrg"></table>
                </div>
            </div>
        </div>
        <div title="相关用户">
            <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
                <div data-options="region:'north',border:false">

                    <div class="datagrid-toolbar">
                        <a key="Add" class="easyui-linkbutton" onclick="addUser()" data-options="iconCls: 'icon-add', plain: true">添加</a>
                        <a key="Delete" class="easyui-linkbutton" onclick="deleteUser()" data-options="iconCls: 'icon-delete', plain: true">移除</a>
                    </div>
                </div>
                <div data-options="region:'center',border:false">

                    <table id="dgUser"></table>
                </div>
            </div>
        </div>
    </div>
</div>

src/Fireasy.Zero.AspNetCore/Areas/Admin/Views/Permission/Function.cshtml
@{
    ViewBag.Title = "功能授权";
    Layout = "~/Views/Shared/_EasyUILayout.cshtml";
}

<script type="text/javascript">
    var roleId = 0;

    $(function () {
        loadRoles();
        loadModules();
        loadUsers();
    });

    function loadRoles() {
        $('#dgRole').datalist({
            url: '@Url.Action("Data", "Role", new { area = "Admin" })',
            fit: true,//自动填充
            singleSelect: true,//单选
            pagination: false,//分页信息
            idField: 'RoleID',
            border: false,
            valueField: 'RoleID',
            textField: 'Name',
            onClickRow: function (index, row) {
                roleId = row.RoleID;
                loadModules();
                loadUsers();
            },
            queryParams: { state: '1' }
        });
    }

    function loadUsers() {
        $('#dgUser').datagrid({
            url: '@Url.Action("GetUsersByRole")?roleId=' + roleId,
            fit: true,//自动填充
            singleSelect: true,//单选
            pagination: true,//分页信息
            rownumbers: true,//显示行号
            pageNumber: 1,//默认显示第一页
            pageSize: 20,//每页的行数
            checkOnSelect: false,
            selectOnCheck: false,
            idField: 'UserID',
            columns: [[

                { field: 'ck', checkbox: true },
                { field: 'Name', title: '姓名', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'OrgName', title: '隶属机构', width: 350, halign: 'center', align: 'left', sortable: true },
                { field: 'Account', title: '帐号', width: 120, halign: 'center', align: 'center', sortable: true }
            ]],
            queryParams: { state: '1' }
        });
    }

    //加载数据
    function loadModules() {
        $('#dgModule').treegrid({
            url: '@Url.Action("GetModulesByRole")?roleId=' + roleId,
            fit: true,//自动填充
            idField: 'id',
            treeField: 'Name',
            columns: [[

                { field: 'Name', title: '模块', width: 260, halign: 'center', align: 'left', formatter: function (value, row) { return formatCheckbox(value, row); } },
                { field: 'Operaters', title: '操作', width: 600, halign: 'center', align: 'left', formatter: formatOperates }
            ]]
        });
    }

    function formatCheckbox(value, row) {
        return '<input did="' + row.id + '" type="checkbox" ' + (row.Permissible ? 'checked' : '') + ' onclick="checkChildren(' + row.id + ', $(this).prop(\'checked\'))" />' + value;
    }

    function formatOperates(value, row) {
        if (row.SysOperates.length == 0) {
            return null;
        }
        var str = '<label style="color:blue"><input id="chkAll_' + row.id + '" type="checkbox" onclick="checkAllOpers(' + row.id + ', $(this).prop(\'checked\'))" />全选</label>&nbsp;';
        $.each(row.SysOperates, function (i, r) {
            str += '<input id="o_' + r.OperID + '" mid="' + row.id + '" oid="' + r.OperID + '" type="checkbox" ' + (r.Permissible ? 'checked' : '') + ' /><label class="lbl" for="o_' + r.OperID + '">' + r.Name + '</label>&nbsp;';
        });
        return str;
    }

    function checkChildren(id, ck) {
        if (ck) {
            var parent = $('#dg').treegrid('getParent', id);
            while (parent != null) {
                $('[did="' + parent.id + '"]').prop('checked', ck);
                parent = $('#dg').treegrid('getParent', parent.id);
            }
        }

        var children = $('#dg').treegrid('getChildren', id);
        $.each(children, function (i, r) {
            $('[did="' + r.id + '"]').prop('checked', ck);
            checkAllOpers(r.id, ck);
        });

        checkAllOpers(id, ck);
    }

    function checkAllOpers(mid, ck) {
        $('input[mid="' + mid + '"]').each(function (i, r) {
            $(r).prop('checked', ck);
        });
    }

    function addUser() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        common.showDialog('@Url.Action("SelectUser")?roleId=' + roleId, '选择用户', 1080, 550, function (users) {
            var postData = new Object();
            postData.roleId = roleId;
            postData.users = JSON.stringify(users);
            $.post('@Url.Action("AddRoleUsers")', postData, function (result) {
                $('#dgUser').datagrid('reload');
            })
        }).max();
    }

    function deleteUser() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        var rows = $('#dgUser').datagrid('getChecked');
        if (rows.length == 0) {
            common.alert('请选择要移除的用户。');
            return;
        }

        var ids = [];
        $.each(rows, function (i, r) {
            ids.push(r.UserID);
        });

        common.confirm('是否从当前角色中移除指定的用户?', function () {
            var postData = new Object();
            postData.roleId = roleId;
            postData.users = JSON.stringify(ids);
            $.post('@Url.Action("DeleteRoleUsers")', postData, function (result) {
                $('#dgUser').datagrid('reload');
            })
        });
    }

    function saveInfo() {
        if (roleId == 0) {
            common.alert('请选择左边的角色。');
            return;
        }

        common.confirm('是否保存权限?', function () {
            var checked = $('input[did]:checked');
            var data = [];
            var opers = {};
            $.each(checked, function (i, c) {
                var did = $(c).attr('did');
                data.push(did);

                opers[did] = [];
                $('input[mid="' + did + '"]:checked').each(function (j, o) {
                    opers[did].push($(o).attr('oid'))
                });
            })

            var postData = new Object();
            postData.roleId = roleId;
            postData.modules = JSON.stringify(data);
            postData.opers = JSON.stringify(opers);

            common.showProcess();

            $.post('@Url.Action("SaveFuncPermissions")', postData, function (result) {
                common.processResult(result);
            })
        });
    }
</script>
@Html.AntiForgeryToken()
<div data-options="region:'west',border:false,split:true,collapsible:true,title:'角色'" style="width:160px">
    <table id="dgRole" style="width:100%"></table>
</div>
<div data-options="region:'center',border:false">
    <div class="easyui-tabs" data-options="fit:true" style="width: 100%; height: 100%">
        <div title="权限设置">
            <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
                <div data-options="region:'north',border:false">
                    <div class="datagrid-toolbar">
                        <a key="Save" class="easyui-linkbutton" onclick="saveInfo()" data-options="iconCls: 'icon-ok', plain: true">保存</a>
                    </div>
                </div>
                <div data-options="region:'center',border:false">
                    <table id="dgModule"></table>
                </div>
            </div>
        </div>
        <div title="相关用户">
            <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
                <div data-options="region:'north',border:false">

                    <div class="datagrid-toolbar">
                        <a key="Add" class="easyui-linkbutton" onclick="addUser()" data-options="iconCls: 'icon-add', plain: true">添加</a>
                        <a key="Delete" class="easyui-linkbutton" onclick="deleteUser()" data-options="iconCls: 'icon-delete', plain: true">移除</a>
                    </div>
                </div>
                <div data-options="region:'center',border:false">

                    <table id="dgUser"></table>
                </div>
            </div>
        </div>
    </div>
</div>