src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/DictItemController.cs
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Fireasy.Zero.AspNetCore.Areas.Base.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class DictItemController : Controller
    {
        private IAdminService _adminService;

        public DictItemController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetDictItems(string typeCode)
        {
            return Json(_adminService.GetDictItems(typeCode));
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/OrgController.cs
using Fireasy.Common.ComponentModel;
using Fireasy.Common.Extensions;
using Fireasy.Web.EasyUI;
using Fireasy.Web.Mvc;
using Fireasy.Zero.Helpers;
using Fireasy.Zero.Models;
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Fireasy.Zero.AspNetCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class OrgController : Controller
    {
        private IAdminService _adminService;

        public OrgController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        /// <summary>
        /// 根据ID获取机构。
        /// </summary>
        /// <param name="id">信息ID。</param>
        /// <returns></returns>
        public async Task<JsonResult> Get(int id)
        {
            var info = await _adminService.GetOrgAsync(id);
            return Json(info);
        }

        /// <summary>
        /// 获取下一个顺序号。
        /// </summary>
        /// <param name="parentId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetNextOrderNo(int? parentId)
        {
            return Json(await _adminService.GetOrgNextOrderNoAsync(parentId));
        }

        /// <summary>
        /// 保存机构。
        /// </summary>
        /// <param name="id">id。</param>
        /// <param name="info">要保存的数据。</param>
        /// <returns>id</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Save(int? id, SysOrg info)
        {
            id = await _adminService.SaveOrgAsync(id, info);
            return Json(Result.Success("保存成功。", id));
        }

        /// <summary>
        /// 保存多个机构。
        /// </summary>
        /// <param name="parentId">隶属机构ID。</param>
        /// <param name="rows">多个机构数据。</param>
        /// <returns></returns>
        public async Task<JsonResult> SaveRows(int? parentId, List<SysOrg> rows)
        {
            await _adminService.SaveOrgsAsync(parentId, rows);
            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 根据查询条件获取机构。
        /// </summary>
        /// <param name="hosting">用来往 <see cref="JsonSerializeOption"/> 里加自定义的转换器。</param>
        /// <param name="id"></param>
        /// <param name="targetId"></param>
        /// <param name="currentId"></param>
        /// <param name="attribute"></param>
        /// <param name="state"></param>
        /// <param name="attType">附加的信息。</param>
        /// <param name="flag"></param>
        /// <returns></returns>
        public async Task<JsonResult> DataDemand([FromServices] JsonSerializeOptionHosting hosting, int? id, int? targetId, int? currentId, OrgAttribute? attribute = null, StateFlags? state = null, ItemFlag? flag = null)
        {
            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Code, s => s.AttributeName, s => s.State);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetOrgsAsync(id, targetId, currentId, state, null, attribute);

            return Json(id != null ? list : ItemFlagHelper.Insert(list, flag, s => new { id = 0, text = s.GetDescription() }));
        }

        /// <summary>
        /// 根据查询条件获取机构。
        /// </summary>
        /// <param name="hosting">用来往 <see cref="JsonSerializeOption"/> 里加自定义的转换器。</param>
        /// <param name="targetId"></param>
        /// <param name="attribute"></param>
        /// <param name="attType">附加的信息。</param>
        /// <param name="corpType">企业类别。</param>
        /// <param name="flag"></param>
        /// <returns></returns>
        public async Task<JsonResult> Data([FromServices] JsonSerializeOptionHosting hosting, int? targetId, OrgAttribute? attribute = null, ItemFlag? flag = null)
        {
            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Code, s => s.AttributeName, s => s.State);
            hosting.Option.Converters.Add(converter);

            var session = HttpContext.GetSession();

            var list = await _adminService.GetOrgsAsync(session.UserID, null, attribute);
            if (targetId != null)
            {
                await ExpandTargetAsync(list, (int)targetId);
            }

            return Json(ItemFlagHelper.Insert(list, flag, s => new { id = 0, text = s.GetDescription() }));
        }

        /// <summary>
        /// 按关键字搜索。
        /// </summary>
        /// <param name="appKey">应用key。</param>
        /// <param name="keyword">关键字。</param>
        /// <returns></returns>
        public async Task<JsonResult> Search(string keyword)
        {
            var list = await _adminService.SearchOrgsAsync(keyword);
            return Json(list);
        }

        /// <summary>
        /// 删除机构。
        /// </summary>
        /// <param name="id">id</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id)
        {
            await _adminService.DeleteOrgAsync(id);
            return Json(Result.Success("删除成功。"));
        }

        /// <summary>
        /// 启用机构。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Enable(int id)
        {
            await _adminService.SetOrgStateAsync(id, StateFlags.Enabled);
            return Json(Result.Success("启用成功。"));
        }

        /// <summary>
        /// 禁用机构。
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> Disable(int id)
        {
            await _adminService.SetOrgStateAsync(id, StateFlags.Disabled);
            return Json(Result.Success("禁用成功。"));
        }

        /// <summary>
        /// 展开到目标节点。
        /// </summary>
        /// <param name="list"></param>
        /// <param name="parentId"></param>
        private async Task ExpandTargetAsync(List<SysOrg> list, int parentId)
        {
            var org = await _adminService.GetOrgAsync(parentId);
            if (org == null)
            {
                return;
            }

            var code = org.Code;
            var length = code.Length;
            var children = list;

            for (var i = 0; i < length; i += 2)
            {
                org = children.Find(s => s.Code == code.Substring(0, i + 2));
                if (org != null)
                {
                    org.IsLoaded = true;
                    children = org.Children;
                }
            }
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Controllers/PermissionController.cs
using Fireasy.Common.ComponentModel;
using Fireasy.Web.EasyUI;
using Fireasy.Web.Mvc;
using Fireasy.Zero.Helpers;
using Fireasy.Zero.Models;
using Fireasy.Zero.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Fireasy.Zero.AspNetCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class PermissionController : Controller
    {
        private IAdminService _adminService;

        public PermissionController(IAdminService adminService)
        {
            _adminService = adminService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SelectUser()
        {
            return View();
        }

        public ActionResult Function()
        {
            return View();
        }

        public ActionResult Data()
        {
            return View();
        }

        public ActionResult Auth()
        {
            return View();
        }

        /// <summary>
        /// 根据角色获取相应的模块及操作。
        /// </summary>
        /// <param name="hosting"></param>
        /// <param name="roleId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetModulesByRole([FromServices] JsonSerializeOptionHosting hosting, int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var converter = new DynamicTreeNodeJsonConverter<SysModule>(s => s.Name, s => s.Permissible, s => s.SysOperates);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetModulesByRoleAsync((int)roleId);
            return Json(list);
        }

        /// <summary>
        /// 根据角色获取相应的机构。
        /// </summary>
        /// <param name="hosting"></param>
        /// <param name="roleId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetOrgsByRole([FromServices] JsonSerializeOptionHosting hosting, int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var converter = new DynamicTreeNodeJsonConverter<SysOrg>(s => s.Name, s => s.Permissible, s => s.FullName);
            hosting.Option.Converters.Add(converter);

            var list = await _adminService.GetOrgsByRoleAsync((int)roleId);
            return Json(list);
        }

        /// <summary>
        /// 获取角色列表。
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetRolesByUser(int userId)
        {
            var list = await _adminService.GetPurviewRolesAsync(userId);
            return Json(list);
        }

        /// <summary>
        /// 根据查询条件获取用户。
        /// </summary>
        /// <param name="orgCode">机构编码</param>
        /// <param name="keyword">关键字</param>
        /// <param name="roleId">角色ID。</param>
        /// <param name="state">启用状态</param>
        /// <returns></returns>
        public async Task<JsonResult> GetUsers(string orgCode, string keyword, int roleId)
        {
            var pager = EasyUIHelper.GetDataPager(HttpContext);
            var sorting = EasyUIHelper.GetSorting(HttpContext);

            var userId = HttpContext.GetSession().UserID;

            sorting = sorting.Replace("SexName", "Sex", "DegreeName", "DegreeNo", "TitleName", "TitleNo");

            var list = await _adminService.GetUsersByRoleExcludeAsync(userId, orgCode, roleId, keyword, pager, sorting);
            return Json(EasyUIHelper.Transfer(pager, list));
        }

        /// <summary>
        /// 保存功能权限。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="modules">勾选的模块ID列表。</param>
        /// <param name="opers">勾选的模块与操作的列表。</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveFuncPermissions(int roleId, List<int> modules, Dictionary<int, List<int>> opers)
        {
            await _adminService.SaveFuncRolePermissions(roleId, modules, opers);

            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 保存数据权限。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="org">勾选的机构ID列表。</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<JsonResult> SaveDataPermissions(int roleId, List<int> orgs)
        {
            await _adminService.SaveOrgRolePermissionsAsync(roleId, orgs);

            return Json(Result.Success("保存成功。"));
        }

        /// <summary>
        /// 根据角色获取相应的用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <returns></returns>
        public async Task<JsonResult> GetUsersByRole(int? roleId)
        {
            if (roleId == null)
            {
                return Json(new string[0]);
            }

            var pager = EasyUIHelper.GetDataPager(HttpContext);
            var sorting = EasyUIHelper.GetSorting(HttpContext);

            var list = await _adminService.GetUsersByRoleAsync((int)roleId, pager, sorting);

            return Json(EasyUIHelper.Transfer(pager, list));
        }

        /// <summary>
        /// 为角色添加多个用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="users">用户ID列表。</param>
        /// <returns></returns>
        public async Task<JsonResult> AddRoleUsers(int roleId, List<int> users)
        {
            await _adminService.AddRoleUsers(roleId, users);

            return Json(Result.Success("添加成功。"));
        }

        /// <summary>
        /// 移除角色中的指定的用户。
        /// </summary>
        /// <param name="roleId">角色ID。</param>
        /// <param name="users">用户ID列表。</param>
        /// <returns></returns>
        public async Task<JsonResult> DeleteRoleUsers(int roleId, List<int> users)
        {
            await _adminService.DeleteRoleUsers(roleId, users);

            return Json(Result.Success("删除成功。"));
        }

        /// <summary>
        /// 保存用户角色。
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="roles"></param>
        /// <returns></returns>
        public async Task<JsonResult> SaveUserRoles(int userId, List<int> roles)
        {
            await _adminService.SaveUserRoles(userId, roles);

            return Json(Result.Success("保存成功。"));
        }
    }
}

src/Fireasy.Zero.AspNetCore/Areas/Admin/Views/User/Edit.cshtml
@model SysUser
@{
    ViewBag.Title = "用户信息";
    Layout = "~/Views/Shared/_EasyUILayout.cshtml";
}
<script src="~/scripts/jquery.uploader.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var id = '@Context.Request.Query["id"]';
    var orgId = '';
    var post = '';

    $(function () {
        loadInfo();
        initUploader();
    });

    //加载机构
    function loadOrgs() {
        $('#cboOrgID').combotree({
            url: "@Url.Action("Data", "Org")?targetId=" + orgId + '&flag=3',
            onLoadSuccess: function () {
                if (orgId != '' && orgId != null) {
                    $('#cboOrgID').combotree('setValue', orgId);
                }
            },
            onSelect: function (row) {
                orgId = row.id;
                loadPost();
            }
        });
    }

    function loadPost() {
        $('#cboPost').combobox({
            url: "@Url.Action("DataByAssign", "OrgPost")?orgId=" + orgId + '&flag=3',
            valueField: 'PostID',
            textField: 'Name',
            onLoadSuccess: function () {
                if (post != '' && post != null) {
                    $('#cboPost').combobox('setValues', post);
                }
            }
        });
    }

    //加载信息
    function loadInfo() {
        if (id !== '') {
            $.getJSON('@Url.Action("Get")?id=' + id, function (data) {
                common.processResult(data, function () {
                    $('#form1').form('load', data);
                    orgId = data.OrgID;
                    post = data.Post;
                    if (data.Photo != '') {
                        $('#photo').attr('src', '../../' + data.Photo);
                        $('#photo').attr('file', data.Photo);
                    }
                    loadOrgs();
                    loadPost();
                });
            });

            $('#btnSaveAndNew').remove();
        }
        else {
            loadOrgs();
        }
    }
    
    //初始化上传插件
    function initUploader() {
        $('.uploader').upload({
            extFilter: 'png;jpg;jpeg;gif',
            action: '@Url.Action("UploadPhoto")?userId=' + id,
            useHttpModule: false,
            onFileExtError: function () {
                common.alert('只允许上传png、jpg、jpeg、gif类型的文件。');
            },
            onComplete: function (result, index, ele) {
                $('#photo').attr('src', "../../" + result);
                $('#photo').attr('file', result);
            }
        });
    }

    //保存信息
    function saveInfo(isNew) {
        if (!$('#form1').form('validate')) {
            return;
        }

        var postData = new Object();

        //将表单填充的内容序列化为json
        var data = $('#form1').form('save');
        data.Photo = $('#photo').attr('file');
        postData["info"] = JSON.stringify(data);
        common.antiToken(postData);

        common.showProcess();
        $.post('@Url.Action("Save")?id=' + id, postData, function (result) {
            common.processResult(result, function () {
                if (isNew) {
                    $('#form1').form('clear');
                }

                common.setReturnValue(true);

                if (common.closeWhenSave && !isNew) {
                    common.closeWindow();
                }
            });
        });
    }

</script>
@Html.AntiForgeryToken()
<div data-options="region:'center',border:false">
    <table class="form-body">

        <tr>
            <td class="addon">帐号</td>
            <td>@Html.TextBox(s => s.Account, new TextBoxSettings { Readonly = true, Editable = false }).Style("width:200px")</td>
            <td rowspan="4" style="padding-left:20px;vertical-align:top;text-align:center">
                <img id="photo" src="~/content/images/photo.png" style="width:120px;height:140px" /><br />
                <a class="uploader">上传头像</a>
            </td>
        </tr>
        <tr>
            <td class="addon">姓名</td>
            <td>@Html.TextBox(s => s.Name).Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">身份证号</td>
            <td>@Html.TextBox(s => s.IDCard).Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">所属部门</td>
            <td>@Html.ComboTree(s => s.OrgID, new ComboTreeSettings { PanelHeight = 400, PanelWidth = 300 }).MarkNoClear().Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">性别</td>
            <td>@Html.ComboBox(s => s.Sex, typeof(Sex), new ComboBoxSettings { Value = "0" }).Style("width:200px").MarkNoClear()</td>
        </tr>
        <tr>
            <td class="addon">学历</td>
            <td>@Html.ComboBox(s => s.DegreeNo, new ComboBoxSettings { Url = Url.Action("GetDictItems", "DictItem") + "?typeCode=Degree", ValueField = "Value", TextField = "Name" }).Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">职称</td>
            <td>@Html.ComboBox(s => s.TitleNo, new ComboBoxSettings { Url = Url.Action("GetDictItems", "DictItem") + "?typeCode=Title", ValueField = "Value", TextField = "Name" }).Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">手机号</td>
            <td>@Html.TextBox(s => s.Mobile).Style("width:200px")</td>
        </tr>
        <tr>
            <td class="addon">邮件</td>
            <td>@Html.TextBox(s => s.Email).Style("width:200px")</td>
        </tr>
    </table>
</div>
<div data-options="region:'south',border:false" class="form-button">
    <a class="easyui-linkbutton" onclick="saveInfo()" id="btnSave" data-options="iconCls:'icon-save'">保存</a>
    <a class="easyui-linkbutton" onclick="saveInfo(true)" id="btnSaveAndNew" data-options="iconCls:'icon-save_new'">保存并新建</a>
    <a class="easyui-linkbutton" onclick="common.closeWindow()" id="btnClose" data-options="iconCls:'icon-cancel'">关闭</a>
</div>

src/Fireasy.Zero.AspNetCore/Areas/Admin/Views/User/Index.cshtml
@{
    ViewBag.Title = "用户管理";
    Layout = "~/Views/Shared/_EasyUILayout.cshtml";
}

<script type="text/javascript">
    $(function () {
        loadOrgs();
        loadUsers();
    });

    function loadOrgs() {
        $('#treOrg').tree({
            url: '@Url.Action("Data", "Org", new { area = "Admin" })',
            idField: 'id',
            treeField: 'text',
            onClick: function (node) {
                $('#dg').datagrid({
                    queryParams: { orgCode: node.Code }
                });
            }
        });
    }

    //加载数据
    function loadUsers() {
        $('#dg').datagrid({
            url: '@Url.Action("Data")',
            fit: true,//自动填充
            singleSelect: true,//单选
            pagination: true,//分页信息
            rownumbers: true,//显示行号
            pageNumber: 1,//默认显示第一页
            pageSize:20,//每页的行数
            idField: 'UserID',
            columns: [[

                { field: 'Name', title: '姓名', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'OrgName', title: '隶属机构', width: 350, halign: 'center', align: 'left', sortable: true },
                { field: 'IDCard', title: '身份证号', width: 200, halign: 'center', align: 'left', sortable: true },
                { field: 'Email', title: '电子邮件', width: 200, halign: 'center', align: 'left', sortable: true },
                { field: 'SexName', title: '性别', width: 60, halign: 'center', align: 'center', sortable: true },
                { field: 'Mobile', title: '手机号码', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'RoleNames', title: '角色', width: 200, halign: 'center', align: 'left', sortable: false },
                { field: 'DegreeName', title: '学历', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'TitleName', title: '职称', width: 120, halign: 'center', align: 'center', sortable: true },
                { field: 'Account', title: '帐号', width: 120, halign: 'center', align: 'center', sortable: true }
            ]],
            rowStyler: function (index, row) {
                if (row.State == 0) {
                    return 'color:red';
                }
            },
            onDblClickRow: function () {
                editInfo();
            },
            queryParams: { state: '1' }
        });
    }

    //工具栏按钮单击事件
    function toolbarClick(key) {
        switch (key) {
            case "Add":
                addInfo();
                break;
            case "Edit":
                editInfo();
                break;
            case "Delete":
                deleteInfo();
                break;
            case "Enable":
                enableInfo();
                break;
            case "Disable":
                disableInfo();
                break;
            case "ResetPwd":
                resetPwd();
                break;
            case "Auth":
                auth();
                break;
        }
    }

    //添加信息
    function addInfo() {
        var node = $('#treOrg').tree('getSelected');
        var orgId = node == null ? '' : node.id;
        var orgCode = node == null ? '' : node.Code;

        common.showDialog('@Url.Action("Add")?orgId=' + orgId + '&orgCode=' + orgCode, '添加用户', 900, 550, function () {
            $('#dg').datagrid('reload');
        });
    }

    //修改信息
    function editInfo() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        common.showDialog('@Url.Action("Edit")?id=' + row.UserID, '修改用户', 600, 500, function () {
            $('#dg').datagrid('reload');
        });
    }

    //删除信息
    function deleteInfo() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        var postData = new Object();
        postData.id = row.UserID;
        common.antiToken(postData);

        common.confirm('你确认要删除[<span class="msg_tip">' + row.Name + '</span>]吗?', function () {
            $.post('@Url.Action("Delete")', postData, function (result) {
                common.processResult(result, function () {
                    $('#dg').datagrid('reload');
                });
            });
        });
    }

    //启用信息
    function enableInfo() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        var postData = new Object();
        postData.id = row.UserID;
        common.antiToken(postData);

        common.confirm('你确认要启用[<span class="msg_tip">' + row.Name + '</span>]吗?', function () {
            $.post('@Url.Action("Enable")', postData, function (result) {
                common.processResult(result, function () {
                    $('#dg').datagrid('reload');
                });
            });
        });
    }

    //禁用信息
    function disableInfo() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        var postData = new Object();
        postData.id = row.UserID;
        common.antiToken(postData);

        common.confirm('你确认要禁用[<span class="msg_tip">' + row.Name + '</span>]吗?', function () {
            $.post('@Url.Action("Disable")', postData, function (result) {
                common.processResult(result, function () {
                    $('#dg').datagrid('reload');
                });
            });
        });
    }

    //重设密码
    function resetPwd() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        var postData = new Object();
        postData.id = row.UserID;
        common.antiToken(postData);

        common.confirm('你确认要重设[<span class="msg_tip">' + row.Name + '</span>]的密码吗?', function () {
            $.post('@Url.Action("ResetPwd")', postData, function (result) {
                common.processResult(result);
            });
        });
    }

    //授权
    function auth() {
        var row = $('#dg').datagrid('getSelected');
        if (row == null) {
            common.alert('请先选择一条记录。');
            return;
        }

        common.showDialog('@Url.Action("Auth", "Permission")?id=' + row.UserID, '用户权限', 600, 500);
    }

    //查询
    function query() {
        var node = $('#treOrg').tree('getSelected');
        var orgCode = node == null ? '' : node.Code;

        $('#dg').datagrid('unselectAll');
        $('#dg').datagrid({
            queryParams: {
                state: $('#txtState').combobox('getValue'),
                orgCode: orgCode,
                keyword: $('#txtKeyword').val()
            }
        });
    }
</script>
@Html.AntiForgeryToken()
<div data-options="region:'center',border:false">
    <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
        <div data-options="region:'north',border:false">
            <div class="datagrid-toolbar">
                @Html.Toolbar()
            </div>
            <div class="query">
                <table>
                    <tr>
                        <td>状态</td>
                        <td><input type="text" id="txtState" class="easyui-combobox" data-options="data: [{value: '',text:'--全部--'},{value: '1',text:'启用'},{value: '0',text:'禁用'}],valueField:'value',textField:'text',editable:false,panelHeight:'auto',value:'1'" style="width:90px" /></td>
                        <td>快速查询</td>
                        <td>
                            <input id="txtKeyword" type="text" class="easyui-textbox enterQuery" data-options="prompt:'姓名、拼音首字母、手机号或帐号'" style="width: 240px" />
                        </td>
                        <td>
                            <a class="easyui-linkbutton" id="btnQuery" onclick="query()" data-options="iconCls:'icon-search'">查询</a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div data-options="region:'center',border:false">
            <div class="easyui-layout" data-options="fit:true" style="width: 100%; height: 100%">
                <div data-options="region:'west',border:true,split:true,collapsible:true" style="width:220px">
                    <table id="treOrg" style="width:100%"></table>
                </div>
                <div data-options="region:'center',border:false">
                    <table id="dg"></table>
                </div>
            </div>
        </div>
    </div>
</div>